### PR TITLE
Cancel PR #51, implementation prohibited

### PR DESCRIPTION
**Pull request by rectoria**
Cancel PR #51, default arguments on virtual or override methods are prohibited.

### CODE REVIEW

**Comment by rectoria** [comment]
@ArthurKnoep Can you elaborate? I don't see the point.

**Comment by ArthurKnoep** [comment]
If we don't put a message on it, nobody will implement it

**Comment by rectoria** [comment]
This request revert master branch to stat PR #50 (commit 080067da5313d9e36796c835b6bbc1498cab63f7). Please do not block this PR since the current master branch implement invalid C++11 syntax. Open new issue if furthermore documentation is required.

**Comment by rectoria** [comment]
This PR is not for compilation purposes, but rather for code compliance. This is not good practice in C++11. If we do not start avoiding bad habits with a small project like this, we will continue to do so, and it will become more and more difficult to stop doing them. We need and we must be impeccable.

**Comment by Hirevo** [comment]
I did some research about this and found an exemple that very well showed the weird quirks that such code enables at [this link](https://stackoverflow.com/a/12140116).
So I now approve this change.

**Pull request merged**
